[project]
name = "nw-data"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit",
    "pandas",
    "plotly",
    "duckdb",
    "python-dotenv",
    "sqlparse>=0.5.3",
    "psycopg2>=2.9.10",
]
